-- ═══════════════════════════════════════════════════
--  ANGADI — Site visits + login events (run in SQL Editor)
--  Locked down like every other table since the July 2026 security
--  pass: RLS on, zero policies, so only the service-role key (used
--  server-side in api/subscribe.js and api/admin.js) can touch these.
--  Nothing here is writable or readable with the public anon key.
-- ═══════════════════════════════════════════════════
create table if not exists site_visits (
  id          bigint generated by default as identity primary key,
  created_at  timestamptz not null default now(),
  path        text,
  visitor_id  text,      -- random id the browser keeps in localStorage; not tied to an account
  referrer    text
);
create index if not exists site_visits_created_at_idx on site_visits(created_at desc);
alter table site_visits enable row level security;

create table if not exists login_events (
  id          bigint generated by default as identity primary key,
  created_at  timestamptz not null default now(),
  user_id     uuid,      -- Supabase auth user id, when known
  name        text,
  email       text,
  phone       text,
  method      text       -- 'email' | 'phone' | 'google'
);
create index if not exists login_events_created_at_idx on login_events(created_at desc);
alter table login_events enable row level security;
-- ═══════════════════════════════════════════════════
